"""Provider-neutral AI errors with customer-friendly wording.

Provider adapters translate SDK/HTTP exceptions into these. Everything above the
adapter layer (router, services, API) only ever sees these types.
"""

from __future__ import annotations

from typing import Any

from app.core.errors import AppError


class AIError(AppError):
    status_code = 502
    code = "ai_error"
    title = "The AI couldn't complete that request"
    message = "Please try again in a moment."
    # Whether trying a different model/provider might succeed.
    failover: bool = False

    def __init__(self, message: str | None = None, *, provider: str | None = None, **kwargs: Any) -> None:
        details = kwargs.pop("details", {}) or {}
        if provider:
            details.setdefault("provider", provider)
        kwargs.setdefault("retryable", self.failover)
        super().__init__(message, details=details, **kwargs)


class AINotConfigured(AIError):
    status_code = 503
    code = "ai_not_configured"
    title = "AI isn't set up yet"
    message = "Connect an AI provider in Settings → AI & Integrations to start creating content."


class AIAuthenticationError(AIError):
    status_code = 502
    code = "ai_auth_failed"
    title = "We couldn't connect to your AI provider"
    message = "Check your API key and try again."


class AIPermissionError(AIError):
    code = "ai_permission_denied"
    title = "Your AI account doesn't have access"
    message = (
        "Your API key works, but it doesn't have access to this model. "
        "Check your provider account or choose another model."
    )


class AIModelNotFound(AIError):
    code = "ai_model_not_found"
    title = "That AI model isn't available"
    message = "The selected model couldn't be found for this account. Choose another model in Settings."
    failover = True


class AIRateLimited(AIError):
    status_code = 429
    code = "ai_rate_limited"
    title = "The AI service is busy"
    message = "You've hit your AI provider's usage limit for now. Wait a minute and try again."
    failover = True


class AIQuotaExceeded(AIError):
    status_code = 402
    code = "ai_quota_exceeded"
    title = "Your AI account is out of credit"
    message = (
        "Your AI provider says this account has no remaining credit or quota. "
        "Top up your provider account and try again."
    )


class AIUnavailable(AIError):
    status_code = 503
    code = "ai_unavailable"
    title = "The AI service is temporarily unavailable"
    message = "The AI provider is having problems right now. Please try again shortly."
    failover = True


class AITimeout(AIError):
    status_code = 504
    code = "ai_timeout"
    title = "That took too long"
    message = "The AI didn't respond in time. Try again, or choose fewer variations or the Fast quality."
    failover = True


class AINetworkError(AIError):
    status_code = 503
    code = "ai_network_error"
    title = "We couldn't reach the AI service"
    message = "Check the internet connection (or the server address for a local AI) and try again."
    failover = True


class AIInvalidOutput(AIError):
    code = "ai_invalid_output"
    title = "The AI returned something we couldn't use"
    message = "We've discarded it to protect your content. Please try again."
    failover = True


class AIRefused(AIError):
    status_code = 422
    code = "ai_refused"
    title = "The AI declined this request"
    message = "Try rephrasing the topic. Some subjects can't be generated by AI providers."


class AIBadRequest(AIError):
    code = "ai_bad_request"
    title = "The AI provider rejected the request"
    message = "This model may not support some features we need. Try a different model or quality setting."
    failover = True
