CREATE TABLE `projects` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`topic` text NOT NULL,
	`target_audience` text NOT NULL,
	`platform` text NOT NULL,
	`objective` text NOT NULL,
	`tone` text NOT NULL,
	`duration` integer NOT NULL,
	`visual_style` text NOT NULL,
	`voice` text NOT NULL,
	`call_to_action` text DEFAULT '',
	`brand_instructions` text DEFAULT '',
	`image_quality` text DEFAULT 'standard',
	`status` text DEFAULT 'draft',
	`script` text,
	`storyboard` text,
	`assets` text DEFAULT '[]',
	`render_job` text,
	`error` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
