"""initial schema

Revision ID: b5fa1538eb1b
Revises: 
Create Date: 2026-10-06 22:03:41.312075

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.base

# revision identifiers, used by Alembic.
revision: str = 'b5fa1538eb1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('workspaces',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('onboarding_completed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('active_brand_id', sa.Uuid(), nullable=True),
    sa.Column('ai_source', sa.String(length=20), nullable=False),
    sa.Column('ai_provider', sa.String(length=40), nullable=True),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_auth_sessions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('brand_profiles',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('products_services', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('tone_of_voice', sa.String(length=40), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('content_pillars', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('writing_preferences', sa.Text(), nullable=False),
    sa.Column('preferred_terminology', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cta_style', sa.String(length=200), nullable=False),
    sa.Column('prohibited_words', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('prohibited_subjects', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('brand_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('default_hashtags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('emoji_style', sa.String(length=20), nullable=False),
    sa.Column('additional_instructions', sa.Text(), nullable=False),
    sa.Column('archived_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_brand_profiles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_profiles'))
    )
    with op.batch_alter_table('brand_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_profiles_workspace_id'), ['workspace_id'], unique=False)

    # workspaces.active_brand_id <-> brand_profiles is circular, so the FK is added afterwards.
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_foreign_key(op.f('fk_workspaces_active_brand_id_brand_profiles'), 'brand_profiles', ['active_brand_id'], ['id'], ondelete='SET NULL')

    op.create_table('provider_settings',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('key_hint', sa.String(length=20), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('tier_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_message', sa.String(length=300), nullable=True),
    sa.Column('last_tested_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_provider_settings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_settings')),
    sa.UniqueConstraint('workspace_id', 'provider', name=op.f('uq_provider_settings_workspace_id'))
    )
    with op.batch_alter_table('provider_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_settings_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name=op.f('uq_workspace_members_workspace_id'))
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('content_generations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('brand_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('quality_requested', sa.String(length=20), nullable=False),
    sa.Column('quality_resolved', sa.String(length=20), nullable=True),
    sa.Column('ai_source', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], name=op.f('fk_content_generations_brand_id_brand_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_content_generations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_content_generations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_generations'))
    )
    with op.batch_alter_table('content_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_generations_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_generations_content_type'), ['content_type'], unique=False)
        batch_op.create_index('ix_content_generations_ws_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('content_items',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('angle', sa.String(length=60), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], name=op.f('fk_content_items_generation_id_content_generations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_content_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items'))
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_items_generation_id'), ['generation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('usage_events',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('generation_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('ai_source', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], name=op.f('fk_usage_events_generation_id_content_generations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_events_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_usage_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index('ix_usage_events_ws_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('saved_content',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('generation_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('generation_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], name=op.f('fk_saved_content_brand_id_brand_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_saved_content_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], name=op.f('fk_saved_content_generation_id_content_generations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_saved_content_item_id_content_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_saved_content_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_content'))
    )
    with op.batch_alter_table('saved_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_content_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_content_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_content_is_favourite'), ['is_favourite'], unique=False)
        batch_op.create_index('ix_saved_content_ws_created', ['workspace_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_workspaces_active_brand_id_brand_profiles'), type_='foreignkey')

    with op.batch_alter_table('saved_content', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_content_ws_created')
        batch_op.drop_index(batch_op.f('ix_saved_content_is_favourite'))
        batch_op.drop_index(batch_op.f('ix_saved_content_content_type'))
        batch_op.drop_index(batch_op.f('ix_saved_content_brand_id'))

    op.drop_table('saved_content')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_events_ws_created')

    op.drop_table('usage_events')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_content_items_generation_id'))

    op.drop_table('content_items')
    with op.batch_alter_table('content_generations', schema=None) as batch_op:
        batch_op.drop_index('ix_content_generations_ws_created')
        batch_op.drop_index(batch_op.f('ix_content_generations_content_type'))
        batch_op.drop_index(batch_op.f('ix_content_generations_brand_id'))

    op.drop_table('content_generations')
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_user_id'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('provider_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_settings_workspace_id'))

    op.drop_table('provider_settings')
    with op.batch_alter_table('brand_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_profiles_workspace_id'))

    op.drop_table('brand_profiles')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    op.drop_table('workspaces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
